Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(main.py:3168978): Gdk-CRITICAL **: 16:52:43.190: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
